# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a739600aa9e4a227c11bbf1fe536a1feba90e5c51cd11e00124fcf8be629fbab5d40e37623d301668a83ab87290a5583fc2e21842fe6d6400c54a4acfac27681

test:
  secret_key_base: 93da7b5240f9f3841ed856a5adbac81735a3cdff9e61914944ee6eea0b48e475c94b6e7cfe960f8246f444fe8eee14aca31be9ce76cfc523248ad60266ed858e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
